// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlQymgDsyX_zJnNZRgbR_2DkFjNzKrgKo',
    appId: '1:1045815003541:web:4611ec61d19dd7b8980e9c',
    messagingSenderId: '1045815003541',
    projectId: 'krcportal-c3123',
    authDomain: 'krcportal-c3123.firebaseapp.com',
    storageBucket: 'krcportal-c3123.firebasestorage.app',
    measurementId: 'G-Z6V01D2REK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA20rMPRRZZSQ7DZgFyieP_wygLDd_9xWw',
    appId: '1:1045815003541:android:c2f6a0eacda459ec980e9c',
    messagingSenderId: '1045815003541',
    projectId: 'krcportal-c3123',
    storageBucket: 'krcportal-c3123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMLVOHQV9Dx3ySRk6kXH62aXQXXqUr5CQ',
    appId: '1:1045815003541:ios:be15b8ceca0affa4980e9c',
    messagingSenderId: '1045815003541',
    projectId: 'krcportal-c3123',
    storageBucket: 'krcportal-c3123.firebasestorage.app',
    iosBundleId: 'com.example.krcportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMLVOHQV9Dx3ySRk6kXH62aXQXXqUr5CQ',
    appId: '1:1045815003541:ios:be15b8ceca0affa4980e9c',
    messagingSenderId: '1045815003541',
    projectId: 'krcportal-c3123',
    storageBucket: 'krcportal-c3123.firebasestorage.app',
    iosBundleId: 'com.example.krcportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlQymgDsyX_zJnNZRgbR_2DkFjNzKrgKo',
    appId: '1:1045815003541:web:e53b4df16fc5fd24980e9c',
    messagingSenderId: '1045815003541',
    projectId: 'krcportal-c3123',
    authDomain: 'krcportal-c3123.firebaseapp.com',
    storageBucket: 'krcportal-c3123.firebasestorage.app',
    measurementId: 'G-HGJJ2REE9S',
  );

}